### ISSUE TITLE
figure out why the admin is displayed as an officer but still has admin functionality

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#110]
![bug](https://cloud.githubusercontent.com/assets/9922999/20366602/c0ace586-ac00-11e6-8bc1-961e26afed4d.png)

**Comment by aeolyus** [comment]
Were officers changed to have admin functionality in general now or was it never changed?

**Comment by varmichelle** [comment]
officers have all admin functionality except viewing user roles in profile, which the admin account has access to even though its role is displayed as officer

**Comment by aeolyus** [comment]
So the roles were never touched, its just a interface issue?

**Comment by varmichelle** [comment]
yeah

**Comment by aeolyus** [comment]
![image](https://cloud.githubusercontent.com/assets/11069305/20418837/31ba8840-ad06-11e6-9ed6-2d30ad0581db.png)
It does look fine from here

**Comment by varmichelle** [comment]
very interesting

**Comment by aeolyus** [comment]
Seems to be commit 63784470bf797a808fdaaccd3d81ec482ae97baa
