### ISSUE TITLE
prevent accidental multiple clicks when paying contribution

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#122]
two things
1. prevent multiple clicks (like immediate)
2. prevent paying contribution if already done so (remove the page from their view and reroute to profile or something)

**Comment by aeolyus** [comment]
Clicking where?

**Comment by varmichelle** [comment]
submit button

**Comment by aeolyus** [comment]
the stripe one or the one on the website
can you explain what you mean by multiple clicks and if there is an issue where/a bug that can be replicated

**Comment by aeolyus** [comment]
2 is done in the ui branch but I still need to finish up some stuff before merging
> issue #120 fixed by bc8fc26300692a7c8b4724d0e4d915c89190c900

**Comment by bananabot1024** [comment]
hm someone should test if it allows multiple submissions bc someone just reported that issue to me

**Comment by aeolyus** [comment]
Ask them where they found this bug and if they can give us instructions on how it was done. Until them I'm going to close this thread

**Comment by varmichelle** [comment]
yep nvm it was a misinterpretation on their side
