### ISSUE TITLE
Update Info - User Profile 

### ISSUE THREAD

**Issue by jacksonchui** [EVSD/EVSD-SITE#13]
Send data from server to client through publish/subscribe.
Client should be able to modify "password" and "email" properties on the server.

**Comment by jacksonchui** [comment]
need to learn how to route to different pages first

**Comment by varmichelle** [comment]
that would be just Router.route() with name of page in parentheses. we have already implemented routing in the old repo on the home page among others, see those for reference

**Comment by jacksonchui** [comment]
thanks, routing is done with flow instead of iron. Have to implement updating.

**Comment by jacksonchui** [comment]
commit 33
