### ISSUE TITLE
Hide/Encrypt Stripe tokens?

### ISSUE THREAD

**Issue by aeolyus** [EVSD/EVSD-SITE#23]

**Comment by jacksonchui** [comment]
the necessary test key is private

**Comment by varmichelle** [comment]
what do you mean by the test key is private? 
the issue is that the keys are defined in settings.json, so publishing them to github will be a security issue

**Comment by jacksonchui** [comment]
the just split the keys into a settings-production and settings-deployment for the respective issues https://themeteorchef.com/snippets/making-use-of-settings-json/
