### ISSUE TITLE
routing not working

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#27]
the correct url is appended, so if I try to route to signup, the url becomes localhost:3000/signup. however, it doesn't navigate to that url, and I have to manually press enter to navigate there. not sure why this isn't working, because it's exactly what worked here: http://meteortips.com/second-meteor-tutorial/iron-router-part-1/ and in the old website.

**Comment by aeolyus** [comment]
Can we switch back to flow router for now

**Comment by jacksonchui** [comment]
I need to add redirection to signup to home when the user successfully signs up.

**Comment by varmichelle** [comment]
I implemented routing (after user inputs signup info) to payContribution, then signupSuccess. there's info on the signupsuccess page that the user needs to read, and they can just use the navbar to navigate to home after.

**Comment by jacksonchui** [comment]
routing works well enough now
