### ISSUE TITLE
profile: roles issue

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#39]
error log:
![image](https://cloud.githubusercontent.com/assets/9922999/17654215/7b2f79aa-6255-11e6-9bd3-38b577f8ecb6.png)

code ref:
![image](https://cloud.githubusercontent.com/assets/9922999/17654219/8d1dc716-6255-11e6-9645-bab8af2f9174.png)

**Comment by varmichelle** [comment]
roles still works so oh well

**Comment by jacksonchui** [comment]
I haven't been able to reproduce that error at all so idk
