### ISSUE TITLE
Check Stripe Payment Signup System

### ISSUE THREAD

**Issue by jacksonchui** [EVSD/EVSD-SITE#4]
Make sure that it works.
Have it as a bigger option than the confirm button.

**Comment by varmichelle** [comment]
dependent on tournament registration
I wasn't able to stay for the entire meeting, but I think someone said it was illegal to force people to pay for the tournament during signup?

**Comment by aeolyus** [comment]
As discussed, just make a big donation button smack dab in the middle under it and hope no one finds out about the fact that they don't have to click it. As for legals, put a inconspicuous button somewhere. Also hope no one finds this comment soon.

**Comment by qinjoshua** [comment]
Also add a popup informing in case the user's account details aren't valid/they didn't put anything there.

**Comment by varmichelle** [comment]
already verified
