### ISSUE TITLE
Last Checkups

### ISSUE THREAD

**Issue by jacksonchui** [EVSD/EVSD-SITE#52]
todo: https://docs.google.com/document/d/17t7xrcEgWNIfes_p1jSdVFBGkrsj4ROUufT3v-A4v2k/edit
- [x] urgent: disable signup button until form completion 
- [x] quickfix for above: informs user to fill in any blank text inputs, added warning to upload waiver
- [x] urgent: keep footer on the bottom
- [x] update readme before release
- [x] urgent: secure the system using Meteor guidelines
- [x] hiding partner and judges in the tournament user signup view don't dynamically change
- [x] Check if user email has already been used to signup
- [x] change navbar order (logout should be placed somewhere more logical)
- [x] urgent: fix second dropdown (member resources) bc nothing happens when it's clicked
- [x] dropdown ugly bc covers content
- [ ] urgent: sidenav disappears if window is made smaller or on mobile/ipad
- [x] Elizabeth Thach misspell on officer list
- [x] urgent: there's two logout buttons, get rid of one
- [x] URGENT: date picker not letting user change month/year for some people only
- [ ] login background img takes forever to render
- [x] alphabetize users (displaying on profile, selecting as partner, logging checks, changing balance)

**Comment by aeolyus** [comment]
It seems like two instances of microphone.jpg is loaded. One from github as a link and the physical one in the file. That may be a factor in speed. Possibly just use the local one?

**Comment by aeolyus** [comment]
- [x] reroute Github link in footer to EVSD-SITE

**Comment by varmichelle** [comment]
basically encompassed in other issues
