### ISSUE TITLE
background images on homepage not rendering after switching tabs and coming back to homepage

### ISSUE THREAD

**Issue by varmichelle** [EVSD/EVSD-SITE#89]

**Comment by aeolyus** [comment]
Issue with routing non-relative images.
`<img src="img.png"/>`
to
`<img src="/path to img.png/>`

> Haven't tested this though

**Comment by varmichelle** [comment]
that might not be the issue bc they're not local image paths
this is one of the paths we used:
`<img src="http://static1.squarespace.com/static/5778195e37c581dd7dee1ac6/t/577b3df3ff7c50a2a386a1bb/1467694592578/Microphone.jpg?format=1500w">`
maybe it's an issue with the parallax, because I don't remember it being an issue before then

**Comment by aeolyus** [comment]
Have we tested them with local paths yet. If not we should @bananabot1024
